### ISSUE TITLE
Having issues getting it working, any ideas?

### ISSUE THREAD

**Issue by snoobie256** [letsila/slim3-jwt-example#1]
root@fileapi:/var/www/slim3-jwt-auth-example# ./vendor/bin/phpunit
PHPUnit 4.8.36 by Sebastian Bergmann and contributors.

E{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6ODA4MCIsImlhdCI6MTUxMjM0MTI0MywiZXhwIjoxNTEzNjM3MjQzLCJjb250ZXh0Ijp7InVzZXIiOnsidXNlcl9sb2dpbiI6Im5lbyIsInVzZXJfaWQiOiIxIn19fQ.DcisO2A07faXPvaqND3DGne_b0w8wfe5ZYikrEwLQjI","user_login":"1"}E{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6ODA4MCIsImlhdCI6MTUxMjM0MTI0MywiZXhwIjoxNTEzNjM3MjQzLCJjb250ZXh0Ijp7InVzZXIiOnsidXNlcl9sb2dpbiI6ImtlYW51IiwidXNlcl9pZCI6IjIifX19.ltFxnmig7zTCIVP8risBAm6nhczyy2rkvmkcVkg9bhU","user_login":"2"}F"No user found"

Time: 395 ms, Memory: 5.50MB

There were 2 errors:

1) Tests\Functional\RoutesTest::testATokenShouldBeReturnAfterAValidUserAuthentication
Trying to get property of non-object

/var/www/slim3-jwt-auth-example/tests/Functional/RoutesTest.php:18

2) Tests\Functional\RoutesTest::testAValidUserShouldHaveAccessToARestrictedEndPoint
Trying to get property of non-object

/var/www/slim3-jwt-auth-example/tests/Functional/RoutesTest.php:30

--

There was 1 failure:

1) Tests\Functional\RoutesTest::testANoneRegisteredUserShouldNotBeAuthenticated
Failed asserting that '' contains "No user found".

/var/www/slim3-jwt-auth-example/tests/Functional/RoutesTest.php:41

FAILURES!
Tests: 3, Assertions: 4, Errors: 2, Failures: 1

**Comment by letsila** [comment]
Hi @snoobie256, this error can occurs when you have misconfigured your database. Please, check if you have implemented correctly the tokens table and specified it correctly in the [settings file](https://github.com/letsila/slim3-jwt-auth-example/blob/master/src/settings.php#L20)

**Comment by letsila** [comment]
However I see that there is an error about "No user found" so maybe there is some issue about the [users.json](https://github.com/letsila/slim3-jwt-auth-example/blob/master/users.json) file access.

**Comment by snoobie256** [comment]
user.json has 777 permission, Database is InnoDB, SQL copied from example

**Comment by snoobie256** [comment]
user.json has 777 permission, Database is InnoDB, SQL copied from example, php-json installed.
no issues with DB connection, it appears to have inserted two tokens.

**Comment by letsila** [comment]
can you var_dump this [variable](https://github.com/letsila/slim3-jwt-auth-example/blob/master/src/routes.php#L14) to see what it returns?

**Comment by snoobie256** [comment]
I've added the var_dump in there, just not sure how to get the output, not famlilar with skilm3-skelton. Only raw PHP were, where I can directly call that file.

**Comment by letsila** [comment]
then just run the unit test as you just did above, you should see the output on the console.

**Comment by snoobie256** [comment]
PHPUnit 4.8.36 by Sebastian Bergmann and contributors.

Earray(2) {
  [0]=>
  array(3) {
    ["user_id"]=>
    string(1) "1"
    ["user_login"]=>
    string(3) "neo"
    ["user_pwd"]=>
    string(3) "neo"
  }
  [1]=>
  array(3) {
    ["user_id"]=>
    string(1) "2"
    ["user_login"]=>
    string(5) "keanu"
    ["user_pwd"]=>
    string(5) "keanu"
  }
}
{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6ODA4MCIsImlhdCI6MTUxMjM0MTI0MywiZXhwIjoxNTEzNjM3MjQzLCJjb250ZXh0Ijp7InVzZXIiOnsidXNlcl9sb2dpbiI6Im5lbyIsInVzZXJfaWQiOiIxIn19fQ.DcisO2A07faXPvaqND3DGne_b0w
8wfe5ZYikrEwLQjI","user_login":"1"}Earray(2) {
  [0]=>
  array(3) {
    ["user_id"]=>
    string(1) "1"
    ["user_login"]=>
    string(3) "neo"
    ["user_pwd"]=>
    string(3) "neo"
  }
  [1]=>
  array(3) {
    ["user_id"]=>
    string(1) "2"
    ["user_login"]=>
    string(5) "keanu"
    ["user_pwd"]=>
    string(5) "keanu"
  }
}

{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6ODA4MCIsImlhdCI6MTUxMjM0MTI0MywiZXhwIjoxNTEzNjM3MjQzLCJjb250ZXh0Ijp7InVzZXIiOnsidXNlcl9sb2dpbiI6ImtlYW51IiwidXNlcl9pZCI6IjIifX19.ltFxnmig7zTCIVP8risBAm6nh
czyy2rkvmkcVkg9bhU","user_login":"2"}Farray(2) {
  [0]=>
  array(3) {
    ["user_id"]=>
    string(1) "1"
    ["user_login"]=>
    string(3) "neo"
    ["user_pwd"]=>
    string(3) "neo"
  }
  [1]=>
  array(3) {
    ["user_id"]=>
    string(1) "2"
    ["user_login"]=>
    string(5) "keanu"
    ["user_pwd"]=>
    string(5) "keanu"
  }
}
"No user found"

**Comment by snoobie256** [comment]
PHP Version => 5.5.9-1ubuntu4.22

System => Linux fileapi 4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64
Build Date => Aug  4 2017 19:36:56
Server API => Command Line Interface
Virtual Directory Support => disabled
Configuration File (php.ini) Path => /etc/php5/cli
Loaded Configuration File => /etc/php5/cli/php.ini
Scan this dir for additional .ini files => /etc/php5/cli/conf.d
Additional .ini files parsed => /etc/php5/cli/conf.d/05-opcache.ini,
/etc/php5/cli/conf.d/10-pdo.ini,
/etc/php5/cli/conf.d/20-json.ini,
/etc/php5/cli/conf.d/20-mysql.ini,
/etc/php5/cli/conf.d/20-mysqli.ini,
/etc/php5/cli/conf.d/20-pdo_mysql.ini,
/etc/php5/cli/conf.d/20-readline.ini

PHP API => 20121113
PHP Extension => 20121212
Zend Extension => 220121212
Zend Extension Build => API220121212,NTS
PHP Extension Build => API20121212,NTS
Debug Build => no
Thread Safety => disabled
Zend Signal Handling => disabled
Zend Memory Manager => enabled
Zend Multibyte Support => provided by mbstring
IPv6 Support => enabled
DTrace Support => enabled

Registered PHP Streams => https, ftps, compress.zlib, compress.bzip2, php, file, glob, data, http, ftp, phar, zip
Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, sslv3, tls
Registered Stream Filters => zlib.*, bzip2.*, convert.iconv.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk

This program makes use of the Zend Scripting Language Engine:
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies


Do you want a full phpinfo(), I could probably copy into pastebin

**Comment by letsila** [comment]
obviously there is no issue with the users.json. Now you should var_dump the [$data](https://github.com/letsila/slim3-jwt-auth-example/blob/master/src/routes.php#L16) variable.

**Comment by snoobie256** [comment]
PHPUnit 4.8.36 by Sebastian Bergmann and contributors.

Earray(2) {
  ["user_login"]=>
  string(3) "neo"
  ["user_password"]=>
  string(3) "neo"
}
{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wL                                                                                                                              jE6ODA4MCIsImlhdCI6MTUxMjM0MTI0MywiZXhwIjoxNTEzNjM3MjQzLCJjb250ZXh0Ijp7InVzZXIiO                                                                                                                              nsidXNlcl9sb2dpbiI6Im5lbyIsInVzZXJfaWQiOiIxIn19fQ.DcisO2A07faXPvaqND3DGne_b0w8wf                                                                                                                              e5ZYikrEwLQjI","user_login":"1"}Earray(2) {
  ["user_login"]=>
  string(5) "keanu"
  ["user_password"]=>
  string(5) "keanu"
}
{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wL                                                                                                                              jE6ODA4MCIsImlhdCI6MTUxMjM0MTI0MywiZXhwIjoxNTEzNjM3MjQzLCJjb250ZXh0Ijp7InVzZXIiO                                                                                                                              nsidXNlcl9sb2dpbiI6ImtlYW51IiwidXNlcl9pZCI6IjIifX19.ltFxnmig7zTCIVP8risBAm6nhczy                                                                                                                              y2rkvmkcVkg9bhU","user_login":"2"}Farray(2) {
  ["user_login"]=>
  string(7) "michael"
  ["user_password"]=>
  string(7) "123pass"
}
"No user found"

Time: 709 ms, Memory: 5.50MB

There were 2 errors:

1) Tests\Functional\RoutesTest::testATokenShouldBeReturnAfterAValidUserAuthentic                                                                                                                              ation
Trying to get property of non-object

/var/www/slim3-jwt-auth-example/tests/Functional/RoutesTest.php:18

2) Tests\Functional\RoutesTest::testAValidUserShouldHaveAccessToARestrictedEndPo                                                                                                                              int
Trying to get property of non-object

/var/www/slim3-jwt-auth-example/tests/Functional/RoutesTest.php:30

--

There was 1 failure:

1) Tests\Functional\RoutesTest::testANoneRegisteredUserShouldNotBeAuthenticated
Failed asserting that '' contains "No user found".

/var/www/slim3-jwt-auth-example/tests/Functional/RoutesTest.php:41

FAILURES!
Tests: 3, Assertions: 4, Errors: 2, Failures: 1.

**Comment by letsila** [comment]
Only the user_login and user_pwd in the users.json are valid, why are you using "michael" and "123pass"? that's what causes the "No user found" error

**Comment by snoobie256** [comment]
I just assumed that was a test, to assume the authentication is properly validating, denying access to improper access.

**Comment by snoobie256** [comment]
Changed to neo:neo

There were 2 errors:

1) Tests\Functional\RoutesTest::testATokenShouldBeReturnAfterAValidUserAuthentication
Trying to get property of non-object

/var/www/slim3-jwt-auth-example/tests/Functional/RoutesTest.php:18

2) Tests\Functional\RoutesTest::testAValidUserShouldHaveAccessToARestrictedEndPoint
Trying to get property of non-object

/var/www/slim3-jwt-auth-example/tests/Functional/RoutesTest.php:30

--

There was 1 failure:

1) Tests\Functional\RoutesTest::testANoneRegisteredUserShouldNotBeAuthenticated
Failed asserting that '' contains "No user found".

/var/www/slim3-jwt-auth-example/tests/Functional/RoutesTest.php:41

FAILURES!
Tests: 3, Assertions: 4, Errors: 2, Failures: 1.

**Comment by letsila** [comment]
I am sorry that's right it is one of the test case.

**Comment by snoobie256** [comment]
<?php

namespace Tests\Functional;

use PDO;

class RoutesTest extends BaseTestCase
{

    public function testATokenShouldBeReturnAfterAValidUserAuthentication()
    {
        // Send post request with credential for authentication.
        $response = $this->runApp('POST', '/authenticate', ['user_login' => 'neo', 'user_password' => 'neo']);

        $this->assertEquals(200, $response->getStatusCode());

        // Then assert that we have three string sequence separated by dot returned as a token.
        $this->assertRegExp('#[a-zA-Z0-9-_](\.[a-zA-Z0-9-_])*$#', json_decode($response->getBody())->token);
    }

    public function testAValidUserShouldHaveAccessToARestrictedEndPoint()
    {
        // Authenticate first
        $response = $this->runApp('POST', '/authenticate', ['user_login' => 'keanu', 'user_password' => 'keanu']);

        $this->assertEquals(200, $response->getStatusCode());

        // Use the returned token to request the restricted endpoint.
        $response = $this->runApp('GET', '/restricted', [],
            ["HTTP_AUTHORIZATION" => json_decode($response->getBody())->token]);

        $this->assertEquals(200, $response->getStatusCode());
        $this->assertContains('This is your secure resource !', (string)$response->getBody());

    }

/*public function testANoneRegisteredUserShouldNotBeAuthenticated()
    {
        $response = $this->runApp('POST', '/authenticate', ['user_login' => 'neo', 'user_password' => 'neo']);
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertContains('No user found', (string)$response->getBody());
    }
*/

}

This is the RoutesTest file btw, not sure maybe some changes recently, Tried looking up the property issue, wasn't that sure. I'm new to PHP. What PHP version are you using?

**Comment by letsila** [comment]
For some reasons the routes are not able to correctly return the token, please check all catched Exception from sql queries as this one by var_dumping https://github.com/letsila/slim3-jwt-auth-example/blob/master/src/routes.php#L48

**Comment by snoobie256** [comment]
Thank you for assisting, I've changed the following code to
 } catch (PDOException $e) {
                var_dump($e->getMessage);
        }
No output so far.

**Comment by letsila** [comment]
Try with all the queries. As I can't have a deep look at your setup nor environment, try to isolate step by step by step  the part of the code that bring to the token by var_dumping and then running the test, or if necessary modify the test cases.

**Comment by letsila** [comment]
I don't think it is related to your PHP version. PHP > 5.5 should be fine.

**Comment by snoobie256** [comment]
Will do, thanks for the help.

**Comment by letsila** [comment]
Console is also not really reliable about logging so you can also try to launch the server with 
_php -S 127.0.0.1:8080 -t public public/index.php_
then use tools like Postman to send request manually to display better log

**Comment by snoobie256** [comment]
FAILURES!
Tests: 3, Assertions: 4, Errors: 2, Failures: 1.
root@fileapi:/var/www/slim3-jwt-auth-example# ./vendor/bin/phpunit
PHPUnit 4.8.36 by Sebastian Bergmann and contributors.

Eobject(stdClass)#70 (5) {
  ["id"]=>
  string(1) "7"
  ["value"]=>
  string(243) "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6ODA4MCIsImlhdCI6MTUxMjM4ODU3MywiZXhwIjoxNTEzNjg0NTczLCJjb250ZXh0Ijp7InVzZXIiOnsidXNlcl9sb2dpbiI6Im5lbyIsInVzZXJfaWQiOiIxIn19fQ.dA__j2HIQGvCzt7YR9HV_LX_hkraba_-qaaCW72vvtk"
  ["user_id"]=>
  string(1) "1"
  ["date_created"]=>
  string(10) "1512388573"
  ["date_expiration"]=>
  string(10) "1513684573"
}
{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6ODA4MCIsImlhdCI6MTUxMjM4ODU3MywiZXhwIjoxNTEzNjg0NTczLCJjb250ZXh0Ijp7InVzZXIiOnsidXNlcl9sb2dpbiI6Im5lbyIsInVzZXJfaWQiOiIxIn19fQ.dA__j2HIQGvCzt7YR9HV_LX_hkraba_-qaaCW72vvtk","user_login":"1"}Eobject(stdClass)#117 (5) {
  ["id"]=>
  string(1) "8"
  ["value"]=>
  string(245) "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6ODA4MCIsImlhdCI6MTUxMjM4ODU3MywiZXhwIjoxNTEzNjg0NTczLCJjb250ZXh0Ijp7InVzZXIiOnsidXNlcl9sb2dpbiI6ImtlYW51IiwidXNlcl9pZCI6IjIifX19.NoEA9TrUmnhfwczgLkSag-N6WjgQm4Q2AjtXRdrv8_g"
  ["user_id"]=>
  string(1) "2"
  ["date_created"]=>
  string(10) "1512388573"
  ["date_expiration"]=>
  string(10) "1513684573"
}
{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6ODA4MCIsImlhdCI6MTUxMjM4ODU3MywiZXhwIjoxNTEzNjg0NTczLCJjb250ZXh0Ijp7InVzZXIiOnsidXNlcl9sb2dpbiI6ImtlYW51IiwidXNlcl9pZCI6IjIifX19.NoEA9TrUmnhfwczgLkSag-N6WjgQm4Q2AjtXRdrv8_g","user_login":"2"}F"No user found"

Time: 666 ms, Memory: 5.50MB

There were 2 errors:

**Comment by snoobie256** [comment]
Okay, I've done some additional tests, I've tried just pulling the ./users.json by using the file_get_contents method and nothing, completely empty. Permission issue or php ini configuration problem perhaps.

Wait nvm, "string(161) "[ { "user_id": "1", "user_login": "test", "user_pwd": "test" }, { "user_id": "2", "user_login": "keanu", "user_pwd": "keanu" } ] " "

**Comment by letsila** [comment]
Yeah as I said earlier this is not an issue with the users.json file as it returns correct result when I asked you to var_dump $data. Try to investigate more on the result of sql queries.

**Comment by snoobie256** [comment]
foreach ($users as $key => $user) {
        if ($user['user_login'] == $login && $user['user_pwd'] == $password) {
            $current_user = $user;
        }

    }
   var_dump($current_user); Getting NULL

**Comment by snoobie256** [comment]
foreach ($users as $key => $user) {
        if ($user['user_login'] == $login && $user['user_pwd'] == $password) {
            $current_user = $user;
        }

    }


   var_dump($current_user);  Getting NULL here, werid.

**Comment by letsila** [comment]
Ok, rather than reading the users.json just declare an array with the same data and assign it to $users.

$users = [
[
'user_login' => 'neo',
'user_pwd' => 'neo'
],
[
'user_login' => 'keanu',
'user_pwd' => 'keanu'
]
];

**Comment by letsila** [comment]
$users = [
        [
            'user_login' => 'neo',
            'user_pwd' => 'neo'
        ],
        [
            'user_login' => 'keanu',
            'user_pwd' => 'keanu'
        ]
    ];

**Comment by snoobie256** [comment]
string(0) ""
bool(false)
{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6ODA4MCIsImlhdCI6MTUxMjM5NDEwOCwiZXhwIjoxNTEzNjkwMTA4LCJjb250ZXh0Ijp7InVzZXIiOnsidXNlcl9sb2dpbiI6bnVsbCwidXNlcl9pZCI6bnVsbH19fQ.mF4fDoAo6P-RF0qMrsV1ZMLfqolsj6YLdi3sDRX95BU","user_login":null}


After setting current_user = "";
